#!/usr/bin/env python3

import os
import sys
import yaml
import time
import argparse
import shutil
import numpy as np
import scipy.optimize as opt
from scipy.spatial.transform import Rotation

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
try:
    from visualize_fingertip_model import FingertipVisualizer
    from stretch4_gripper_modeling_and_control import calibration_utils as cu
except ImportError:
    print("Error: visualize_fingertip_model.py not found. Are you running this in the correct directory?")
    sys.exit(1)

def matrix_from_se3_params(params):
    # params: [tx, ty, tz, rx, ry, rz]
    T = np.eye(4)
    T[:3, 3] = params[:3]
    T[:3, :3] = Rotation.from_rotvec(params[3:6]).as_matrix()
    return T

def se3_params_from_matrix(T):
    params = np.zeros(6)
    params[:3] = T[:3, 3]
    params[3:6] = Rotation.from_matrix(T[:3, :3]).as_rotvec()
    return params

def get_error(T_target, T_pred):
    pos_err = np.linalg.norm(T_pred[:3, 3] - T_target[:3, 3])
    R_err = T_pred[:3, :3] @ T_target[:3, :3].T
    trace = np.clip(np.trace(R_err), -1.0, 3.0)
    angle_err = np.arccos((trace - 1.0) / 2.0)
    return pos_err, angle_err

def optimize_mirror(T_targets, T_sources):
    """
    Finds M_G and M_L in SE(3) such that T_target_i ~ M_G @ T_source_i @ M_L for all i.
    """
    # 12 parameters: 6 for M_G, 6 for M_L
    # Warm start: 
    # M_L: 180 deg rotation about X axis (local flip) -> rotvec = [pi, 0, 0]
    # M_G: reflection around Y=0 plane in translation, maybe identity for rot. We will use 0.
    
    init_params = np.zeros(12)
    init_params[6 + 3] = np.pi # M_L rotvec_x = pi

    def loss(params):
        M_G = matrix_from_se3_params(params[:6])
        M_L = matrix_from_se3_params(params[6:12])
        
        total_loss = 0.0
        for T_t, T_s in zip(T_targets, T_sources):
            T_p = M_G @ T_s @ M_L
            pos_err, angle_err = get_error(T_t, T_p)
            total_loss += (pos_err * 100.0)**2 + (angle_err)**2  # roughly 1cm ~ 0.01 error, angular 1 rad ~ 1 error
        return total_loss

    print("Optimizing SE(3) mirror transform... this may take a moment.")
    res = opt.minimize(loss, init_params, method='L-BFGS-B', options={'maxiter': 5000})
    
    M_G = matrix_from_se3_params(res.x[:6])
    M_L = matrix_from_se3_params(res.x[6:12])
    
    # Calculate final errors
    pos_errs = []
    angle_errs = []
    for T_t, T_s in zip(T_targets, T_sources):
        T_p = M_G @ T_s @ M_L
        pos_err, angle_err = get_error(T_t, T_p)
        pos_errs.append(pos_err)
        angle_errs.append(angle_err)
        
    res_dict = {
        'M_G': M_G.tolist(),
        'M_L': M_L.tolist(),
        'mae_pos_m': float(np.mean(pos_errs)),
        'mae_angle_rad': float(np.mean(angle_errs))
    }
    return res_dict

def clean_float(val):
    if isinstance(val, (np.float32, np.float64, float)):
        return float(val)
    elif isinstance(val, (np.ndarray, list, tuple)):
        return [clean_float(x) for x in val]
    elif isinstance(val, dict):
        return {k: clean_float(v) for k, v in val.items()}
    return val

def main():
    parser = argparse.ArgumentParser(description='Optimize SE(3) mirror transforms connecting the left and right fingertip trajectories of a kinematic model.')
    parser.add_argument('model_path', type=str, nargs='?', default=None, help='Path to the model YAML file. If not provided, defaults to the latest fleet calibration model.')
    args = parser.parse_args()
    
    if args.model_path is None:
        args.model_path = cu.get_default_model_path()
        if args.model_path:
            print(f"No model path provided. Defaulting to fleet calibration: {args.model_path}")
        else:
            print("Error: No model path provided and could not locate latest_model_planar.yaml in fleet directory.")
            sys.exit(1)
            
    model_path = os.path.abspath(args.model_path)
    if not os.path.exists(model_path):
        print(f"File not found: {model_path}")
        sys.exit(1)
        
    model = FingertipVisualizer(model_path)
    
    # Sample points across pos_pct
    pcts = np.linspace(-100, 300, 200)
    
    T_left_list = []
    T_right_list = []
    
    for pct in pcts:
        pos_l, F_l = model.predict('left', pct, direction='closing')
        pos_r, F_r = model.predict('right', pct, direction='closing')
        
        if pos_l is not None and pos_r is not None:
            T_l = np.eye(4)
            T_l[:3, :3] = F_l
            T_l[:3, 3] = pos_l
            T_left_list.append(T_l)
            
            T_r = np.eye(4)
            T_r[:3, :3] = F_r
            T_r[:3, 3] = pos_r
            T_right_list.append(T_r)
            
    if len(T_left_list) < 10:
        print("Not enough valid poses generated by the model.")
        sys.exit(1)
        
    print(f"Extracted {len(T_left_list)} paired configurations.")
    
    # R -> L
    print("\n--- Fitting Transform: Right to Left ---")
    res_R2L = optimize_mirror(T_left_list, T_right_list)
    print(f"Result MAE: Pos: {res_R2L['mae_pos_m']*1000:.2f} mm, Angle: {np.rad2deg(res_R2L['mae_angle_rad']):.2f} deg")

    # L -> R
    print("\n--- Fitting Transform: Left to Right ---")
    res_L2R = optimize_mirror(T_right_list, T_left_list)
    print(f"Result MAE: Pos: {res_L2R['mae_pos_m']*1000:.2f} mm, Angle: {np.rad2deg(res_L2R['mae_angle_rad']):.2f} deg")
    
    model_basename = os.path.basename(model_path)
    output_basename = f"mirror_transforms_{model_basename}"
    output_path = os.path.join(os.path.dirname(model_path), output_basename)
    
    current_time_str = time.strftime("%Y%m%d_%H%M%S")
    out_yaml = {
        'metadata': {
            'description': 'SE(3) Mirror Transforms for predicting one fingertip from the other',
            'base_model_filename': model_basename,
            'timestamp': current_time_str
        },
        'right_to_left': clean_float(res_R2L),
        'left_to_right': clean_float(res_L2R)
    }
    
    with open(output_path, 'w') as f:
        yaml.dump(out_yaml, f, sort_keys=False, default_flow_style=False)
        
    print(f"\nSaved mirror transforms cleanly to: {output_path}")

    # Save a copy to the standard Hello Robot calibration directory
    fleet_path = os.environ.get('HELLO_FLEET_PATH')
    # Default to unknown if HELLO_FLEET_ID isn't found
    fleet_id = os.environ.get('HELLO_FLEET_ID', 'unknown')
    if fleet_path and fleet_id and fleet_id != 'unknown':
        calib_gripper_dir = os.path.join(fleet_path, fleet_id, 'calibration_gripper')
        os.makedirs(calib_gripper_dir, exist_ok=True)
        latest_path = os.path.join(calib_gripper_dir, "latest_mirror_transforms.yaml")
        shutil.copy2(output_path, latest_path)
        print(f"Copied model to fleet directory: {latest_path}")

if __name__ == '__main__':
    main()
