[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stretch4_gripper_modeling_and_control"
version = "0.1.0"
description = "Methods for visually and kinematically estimating the poses of the robot’s fingertips."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "opencv-python",
    "scipy",
    "pyyaml",
    "pyzmq",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
stretch4_gripper_modeling_and_control = ["*.urdf"]
